# clickhouse-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: signoz
spec:
  ports:
  - port: 8123
    name: http
  - port: 9000
    name: tcp
  selector:
    app: clickhouse
